# ===============================
# Application
# ===============================
spring.application.name=auth-service
server.port=4000
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
app.frontend.verify-url=${VERIFY_EMAIL_URL:http://localhost:4200/auth/verify}
app.frontend.reset-password-url=${RESET_PASSWORD_EMAIL_URL:http://localhost:4200/reset-password}

# ===============================
# Datasource
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ===============================
# Management / Actuator
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show.details=always

# Metrics Prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}

# ===============================
# Tracing / Correlation
# ===============================
# Probabilite d'echantillonnage des traces (1.0 = toutes les requetes) : Passer a� 0.1 en prod
management.tracing.sampling.probability=1.0
management.tracing.enabled=true
management.tracing.log-correlation.enabled=true
management.tracing.baggage.enabled=true

management.otlp.tracing.endpoint=http://tempo:4318/v1/traces

# Pattern pour afficher traceId/spanId dans les logs
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# ===============================
# OpenTelemetry Exporter (OTLP)
# ===============================
otel.traces.exporter=otlp
otel.instrumentation.logback-mdc.enabled= true
otel.exporter.otlp.endpoint=http://tempo:4318
otel.resource.attributes=service.name=${spring.application.name}

# ===============================
# Security / JWT
# ===============================
application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=${JWT_EXPIRATION}
application.security.jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRATION}

# ===============================
# OpenAPI / Swagger
# ===============================

openapi.service.title=Auth-service Documentation
openapi.service.version=1.0.0
openapi.service.url=http://localhost:4000

springdoc.api-docs.path=/auth-service/v3/api-docs
springdoc.swagger-ui.path=/auth-service/swagger-ui.html

spring.cloud.config.enabled=false
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}


# ===============================
# RabbitMq
# ===============================
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

rabbitmq.exchange.email.name=${RABBIT_EXCHANGE_NAME}
rabbitmq.binding.email.name=${RABBIT_ROUTING_KEY}
rabbitmq.queue.email.name=${RABBIT_QUEUE_NAME}
