# ===============================
# Application
# ===============================
spring.application.name=auth-service
server.port=4000
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# ===============================
# Datasource
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ===============================
# Management / Actuator
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show.details=always

# Metrics Prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}

# ===============================
# Tracing / Correlation
# ===============================
# Probabilité d'échantillonnage des traces (1.0 = toutes les requêtes) : Passer à 0.1 en prod
management.tracing.sampling.probability=1.0
management.tracing.enabled=true
management.tracing.log-correlation.enabled=true
management.tracing.baggage.enabled=true

management.otlp.tracing.endpoint=http://tempo:4318/v1/traces

# Pattern pour afficher traceId/spanId dans les logs
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# ===============================
# OpenTelemetry Exporter (OTLP)
# ===============================
otel.traces.exporter=otlp
otel.instrumentation.logback-mdc.enabled= true
otel.exporter.otlp.endpoint=http://tempo:4318
otel.resource.attributes=service.name=${spring.application.name}

# ===============================
# Security / JWT
# ===============================
application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=${JWT_EXPIRATION}
application.security.jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRATION}
