spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:gateway_redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: ${SPRING_DATA_REDIS_TIMEOUT:2000ms}
  cloud:
    gateway:
    # Configuration CORS globale
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins:
#              - "http://localhost:3000"
#              - "http://localhost:4200"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#              - PATCH
#            allowedHeaders:
#              - "*"
#            exposedHeaders:
#              - Authorization
#              - Content-Type
#            allowCredentials: true
#            maxAge: 3600

      routes:
        - id: auth_login
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/authenticate
            - Method=POST
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 5
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: authLoginCircuitBreaker
                fallbackUri: forward:/fallback/auth
        - id: auth_register
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/register
            - Method=POST
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 4
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: authRegisterCircuitBreaker
                fallbackUri: forward:/fallback/auth
        - id: auth_logout
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/logout
            - Method=POST
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: authLogoutCircuitBreaker
                fallbackUri: forward:/fallback/auth
        - id: auth_service_catch_all
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth
        - id: auth_docs
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/v3/api-docs/**
            - Method=GET

# Configuration Resilience4j Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      authAuthenticateCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      
      authRegisterCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      
      authRefreshCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      
      authLogoutCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      
      authServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  
  # Configuration Resilience4j Time Limiter
  timelimiter:
    instances:
      authAuthenticateCircuitBreaker:
        timeoutDuration: 3s
      authRegisterCircuitBreaker:
        timeoutDuration: 3s
      authRefreshCircuitBreaker:
        timeoutDuration: 3s
      authLogoutCircuitBreaker:
        timeoutDuration: 3s
      authServiceCircuitBreaker:
        timeoutDuration: 3s

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /auth-service/v3/api-docs
        name: Auth Service
        primaryName: Auth Service
