spring.config.import=classpath:application.yml
logging.level.org.springframework.cloud.gateway.filter.ratelimit.RedisRateLimiter=DEBUG
logging.level.org.springframework.cloud.gateway.filter.factory.RequestRateLimiterGatewayFilterFactory=DEBUG

spring.application.name=gateway-service
server.port=8888
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.cloud.config.enabled=false
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
eureka.instance.prefer-ip-address=true

# ===============================
# Management / Actuator
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show.details=always

# Metrics Prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}

# ===============================
# Tracing / Correlation
# ===============================
# Probabilite d'echantillonnage des traces (1.0 = toutes les requetes) : Passer a� 0.1 en prod
management.tracing.sampling.probability=1.0
management.tracing.enabled=true
management.tracing.log-correlation.enabled=true
management.tracing.baggage.enabled=true

management.otlp.tracing.endpoint=http://tempo:4318/v1/traces

# Pattern pour afficher traceId/spanId dans les logs
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# ===============================
# OpenTelemetry Exporter (OTLP)
# ===============================
otel.traces.exporter=otlp
otel.instrumentation.logback-mdc.enabled= true
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
otel.resource.attributes=service.name=${spring.application.name}

# ===============================
# OpenAPI / Swagger
# ===============================

openapi.service.title=Gateway-service Documentation
openapi.service.version=1.0.0
openapi.service.url=http://localhost:8888