# ===============================
# Application
# ===============================
spring.application.name=subscription-service
server.port=4001
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

app.frontend.url=${FRONTEND_URL:http://localhost:4200}

# ===============================
# Datasource
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ===============================
# Management / Actuator
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show.details=always

# Metrics Prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}

# ===============================
# Tracing / Correlation
# ===============================
# Probabilite d'echantillonnage des traces (1.0 = toutes les requetes) : Passer a� 0.1 en prod
management.tracing.sampling.probability=1.0
management.tracing.enabled=true
management.tracing.log-correlation.enabled=true
management.tracing.baggage.enabled=true

management.otlp.tracing.endpoint=http://tempo:4318/v1/traces

# Pattern pour afficher traceId/spanId dans les logs
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# ===============================
# OpenTelemetry Exporter (OTLP)
# ===============================
otel.traces.exporter=otlp
otel.instrumentation.logback-mdc.enabled= true
otel.exporter.otlp.endpoint=http://tempo:4318
otel.resource.attributes=service.name=${spring.application.name}

# ===============================
# OpenAPI / Swagger
# ===============================

openapi.service.title=Subscription-service Documentation
openapi.service.version=1.0.0
openapi.service.url=http://localhost:4001

springdoc.api-docs.path=/subscription-service/v3/api-docs
springdoc.swagger-ui.path=/subscription-service/swagger-ui.html

spring.cloud.config.enabled=false
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

# ===============================
# Stripe
# ===============================

stripe.api.key=${STRIPE_SECRET_KEY:sk_test_your_stripe_secret_key}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:whsec_your_webhook_secret}

# ===============================
# Service Payment
# ===============================

services.payment.url=${PAYMENT_SERVICE_URL:http://localhost:4002}
