apiVersion: 1

contactPoints:
  - orgId: 1
    name: email_alerts_gmail
    receivers:
      - uid: email_alerts_gmail_receiver
        type: email
        settings:
          addresses: $GF_SMTP_USER