apiVersion: 1

policies:
  - orgId: 1
    name: cpu_usage_alert_policy
    receiver: email_alerts_gmail
    group_by: ['alertname', 'instance']
    matchers:
      - alertname = TestCPUUsage
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h

  - orgId: 1
    name: instance_down_policy
    receiver: email_alerts_gmail
    matchers:
      - alertname = InstanceDown
    group_by: ['alertname', 'instance']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h

  - orgId: 1
    name: default_policy
    receiver: email_alerts_gmail
    group_by: ['alertname']
    group_wait: 30s
    group_interval: 10m
    repeat_interval: 2h