name: Reusable CI Workflow

on:
    workflow_call:
        inputs:
            service-path:
                required: true
                type: string
            
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 25
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '25'
                  cache: 'maven'

            - name: Cache SonarQube packages
              uses: actions/cache@v4
              with:
                path: ~/.sonar/cache
                key: ${{ runner.os }}-sonar
                restore-keys: ${{ runner.os }}-sonar

            - name: Execute Test and Code Quality Analysis
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: |
                cd ${{ inputs.service-path }}
                mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar jacoco:check \
                    --file pom.xml \
                    -DskipTests \
                    -Dsonar.projectKey=Mzk-Ali_app_ms_simswap \
                    -Dsonar.host.url=https://sonarcloud.io
            - name: Build and Test Service
              run: |
                cd ${{ inputs.service-path }}
                mvn clean verify