- targets:
    - 'auth-service:4000'
    - 'subscription-service:4001'
    # - 'profile-service:9090'
    # - 'notification-service:9090'
    # - 'gateway:9090'
  labels:
    app: 'app-ms-simswap'
    environment: 'dev'